"""Updated runtime module for Billy v2.

This version adjusts the BillyRuntime constructor to accept an optional
configuration dictionary and default to an empty dictionary when none is
provided. This change ensures that the runtime can be instantiated without
arguments (e.g., `BillyRuntime()`) and prevents errors if callers pass
unexpected keyword arguments.
"""

import yaml
from pathlib import Path

from . import llm_api
from .charter import load_charter

# --- HARD GUARDRAILS (fast stability) ---
FORBIDDEN_IDENTITY_PHRASES = (
    "i'm an ai",
    "i am an ai",
    "i’m an ai",
    "artificial intelligence",
    "chatbot",
    "language model",
    "llm",
    "assistant",
    "conversational ai",
)

# Deterministic fallback identity/purpose (authoritative, no LLM needed)
IDENTITY_FALLBACK = (
    "I am Billy — a digital Farm Hand and Foreman operating inside the Farm."
)


class BillyRuntime:
    def __init__(self, config: dict | None = None) -> None:
        """Initialize the runtime.

        Args:
            config: Optional configuration dictionary. If not provided or None,
                an empty dict will be used. This allows the runtime to be
                instantiated without any parameters, preventing failures when
                unexpected keyword arguments are passed.
        """
        # Default to an empty config to avoid missing-key errors
        self.config = config or {}

    def _identity_guard(self, user_input: str, answer: str) -> str:
        """A placeholder implementation for identity guardrails.

        This method currently returns the answer unchanged but can be extended
        to enforce guardrails on the runtime's responses based on user input.

        Args:
            user_input: The input provided by the user.
            answer: The answer generated by the runtime.

        Returns:
            The possibly modified answer.
        """
        return answer

    # Additional methods can be defined here as needed
